USE DB_EASYBOX
GO
CREATE TABLE ROLES(
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR(30) UNIQUE
)
GO
CREATE TABLE USUARIOS(
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(50) NOT NULL UNIQUE,
	hashpass VARCHAR(200) NOT NULL UNIQUE,
	img_root VARCHAR(150) NULL,
	id_rol INT NOT NULL FOREIGN KEY REFERENCES ROLES(id),
	activo BIT NOT NULL,
	creacion DATETIME NOT NULL,
)
GO
CREATE TABLE CAJAS (
	id_usuario INT PRIMARY KEY,
	saldo_pesos MONEY,
	saldo_dolares MONEY
)

select * from USUARIOS